let openBtn = document.getElementById('open-btn'),
		name = document.getElementsByClassName('name')[0],
		nameValue = document.getElementsByClassName('name-value')[0],
		budget = document.getElementsByClassName('budget')[0],
		budgetVgoodsalue = document.getElementsByClassName('budget-value')[0],
		goods = document.getElementsByClassName('goods')[0],
		goodsValue = document.getElementsByClassName('goods-value')[0],
		items = document.getElementsByClassName('items')[0],
		itemsValue = document.getElementsByClassName('items-value')[0],
		employers = document.getElementsByClassName('employers')[0],
		employersValue = document.getElementsByClassName('employers-value')[0],
		discount = document.getElementsByClassName('discount')[0],
		discountValue = document.getElementsByClassName('discount-value')[0],
		isopen = document.getElementsByClassName('isopen')[0],
		isopenValue = document.getElementsByClassName('isopen-value')[0],

		goodsItems = document.getElementsByClassName('goods-item'),
		goodsBtn = document.getElementsByTagName('button')[1],
		budgetBtn = document.getElementsByTagName('button')[2],
		employersBtn = document.getElementsByTagName('button')[3],
		chooseItem = document.querySelector('#items'),
		timeValue = document.querySelector('#time'),
		countBudgetValue = document.querySelector('#budget'),
		hireEmployersItem = document.querySelectorAll('.hire-employers-item');

